name: Lint Docs

on:
  push:
    branches:
    - master
    paths:
    - "*.md"
    - "**/*.md"
    - ".github/workflows/docs-lint.yml"
  pull_request:
    paths:
    - "*.md"
    - "**/*.md"
    - ".github/workflows/docs-lint.yml"
