name: Build

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  minitest:
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      CI: true
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.0"]
        gemfile: [
          "gemfiles/rails6.gemfile",
        ]
        include:
        # BLOCKED: https://github.com/zdennis/activerecord-import/issues/736
        # - ruby: "3.0"
        #   gemfile: "gemfiles/railsmaster.gemfile"
        - ruby: "2.6"
          gemfile: "gemfiles/rails6.gemfile"
    steps:
    - uses: actions/checkout@v2
    - name: Install system deps
      run: |
        sudo apt-get update
        sudo apt-get install libsqlite3-dev
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run Minitest
      run: |
        bundle exec rake test
